    teleop_twist_joy_node:
      ros__parameters:
        axis_linear:  # Mặc định là linear.x
          x: 1        
        scale_linear:
          x: 1.13      # Tốc độ thẳng tối đa (m/s) - tương ứng với động cơ 333 RPM
        scale_linear_turbo:
          x: 1.13      # Giữ ở max, vì control.yaml sẽ giới hạn
                        # (Hoặc đặt thấp hơn nếu muốn chế độ turbo chậm hơn max)
        axis_angular: # Mặc định là angular.z
          yaw: 0      
        scale_angular:
          yaw: 2.0    # Vận tốc xoay tối đa (rad/s) - đồng bộ với control.yaml
        scale_angular_turbo:
          yaw: 2.0    # Giữ ở max, đồng bộ với giới hạn trong control.yaml


        enable_button: 4          # Nút L1 (Shoulder Left) làm deadman switch (cần giữ để di chuyển)
                                  # Nếu không muốn deadman, đặt là -1 hoặc bỏ dòng này
                                  # và đảm bảo `require_enable_button` là false (mặc định là true)
        
        # enable_turbo_button: 5  # Nút R1 (Shoulder Right) để kích hoạt turbo
        
        # Invert axes if necessary (PS4 controller often needs this)
        # invert_linear_x: true
        # invert_angular_yaw: true 
        
        # Nếu bạn muốn sử dụng các nút khác hoặc các trục khác, bạn cần tìm ra chỉ số của chúng.
        # Một cách là echo topic /joy khi joy_node đang chạy và di chuyển/nhấn các nút.
        # sensor_msgs/msg/Joy có hai mảng: axes và buttons. Chỉ số trong mảng đó là thứ bạn cần.